### ISSUE TITLE
Some confusion about baseline algorithms such as VNS, SA, GA.

### ISSUE THREAD

**Issue by SONGSONG729** [mingfan321/HADRL#1]
Hello, dear author, 
I am very interested in your work. In the comparative analysis, you compared several baselines such as  VNS, SA, GA. Do these baselines have code references or paper references?

**Comment by two-tigger** [comment]
> Hello, dear author, I am very interested in your work. In the comparative analysis, you compared several baselines such as VNS, SA, GA. Do these baselines have code references or paper references?

Hello can you run this code, I have a problem during the run, can you ask how you run it?
Here it is:
Traceback (most recent call last):
  File "D:/ProgramData/PycharmProjects/HADRL-main/run.py", line 176, in <module>
    run(get_options())
  File "D:/ProgramData/PycharmProjects/HADRL-main/run.py", line 106, in run
    baseline = RolloutBaseline(model, problem, opts)
  File "D:\ProgramData\PycharmProjects\HADRL-main\reinforce_baselines.py", line 151, in __init__
    self._update_model(model, epoch)
  File "D:\ProgramData\PycharmProjects\HADRL-main\reinforce_baselines.py", line 171, in _update_model
    self.bl_vals = rollout(self.model, self.dataset, self.opts).cpu().numpy()
  File "D:\ProgramData\PycharmProjects\HADRL-main\train.py", line 43, in rollout
    in tqdm(DataLoader(dataset, batch_size=opts.eval_batch_size), disable=opts.no_progress_bar)
  File "D:\ProgramData\PycharmProjects\HADRL-main\train.py", line 42, in <listcomp>
    for bat
  File "D:\ProgramData\PycharmProjects\HADRL-main\train.py", line 37, in eval_model_bat
    cost, _ = model(move_to(bat, opts.device))
  File "D:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\ProgramData\PycharmProjects\HADRL-main\nets\attention_model.py", line 144, in forward
    _log_p, pi = self._inner(input, embeddings)
  File "D:\ProgramData\PycharmProjects\HADRL-main\nets\attention_model.py", line 248, in _inner
    batch_size = state.ids.size(0)
  File "D:\ProgramData\PycharmProjects\HADRL-main\problems\mcsrp\state_mcsrp.py", line 41, in __getitem__
    assert torch.is_tensor(key) or isinstance(key, slice)  # If tensor, idx all tensors by this tensor:
AssertionError
  0%|          | 0/10 [00:01<?, ?it/s]
